name: plycolmap
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.12.2=hca03da5_0
  - ceres-solver=2.2.0=cpuhad914a0_8
  - colmap=3.11.1=cpuh0af2650_3
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - eigen=3.4.0=h49c215f_1
  - expat=2.7.3=h50f4ffc_3
  - flann=1.9.2=hb343761_5
  - freeimage=3.18.0=h2e169f6_22
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - gflags=2.2.2=hf9b8971_1005
  - glew=2.1.0=h9f76cd9_2
  - glib=2.84.4=h863a760_0
  - glib-tools=2.84.4=hff4a405_0
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=h7bae524_2
  - gst-plugins-base=1.24.11=h3c5c1d0_0
  - gstreamer=1.24.11=hfe24232_0
  - hdf5=1.14.6=nompi_hd3baa01_104
  - icu=75.1=hfee45f7_0
  - imageio=2.37.0=pyhfb79c49_0
  - imath=3.1.12=h025cafa_0
  - jasper=4.2.8=hc0e5025_0
  - jxrlib=1.1=h93a5062_3
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libaec=1.1.4=h51d1e36_0
  - libamd=3.3.3=h5087772_7100102
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libblas=3.11.0=4_h51639a9_openblas
  - libboost=1.86.0=h29978a0_2
  - libbtf=2.3.2=h99b4a89_7100102
  - libcamd=3.3.3=h99b4a89_7100102
  - libcblas=3.11.0=4_hb0561ab_openblas
  - libccolamd=3.3.4=h99b4a89_7100102
  - libcholmod=5.3.1=hbba04d7_7100102
  - libclang-cpp17=17.0.6=default_hf90f093_8
  - libclang13=19.1.7=default_h6e8f826_5
  - libcolamd=3.3.4=h99b4a89_7100102
  - libcurl=8.17.0=hdece5d2_0
  - libcxsparse=4.4.1=h9e79f82_7100102
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=h50f4ffc_3
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_15
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libgfortran=15.2.0=h07b0088_15
  - libgfortran5=15.2.0=hdae7583_15
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - libklu=2.3.5=h4370aa4_7100102
  - liblapack=3.11.0=4_hd9741b5_openblas
  - libldl=3.3.2=h99b4a89_7100102
  - libllvm17=17.0.6=hc4b4ae8_3
  - libllvm19=19.1.7=hc4b4ae8_1
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopus=1.5.2=h48c0fde_0
  - libparu=1.0.0=h317a14d_7100102
  - libpng=1.6.53=hfab5511_0
  - libpq=17.7=h944245b_1
  - libraw=0.21.4=h62a31ad_0
  - librbio=4.3.4=h99b4a89_7100102
  - libspex=3.2.3=h15d103f_7100102
  - libspqr=4.3.4=h775d698_7100102
  - libsqlite=3.51.1=h9a5124b_0
  - libssh2=1.11.1=h1590b86_0
  - libsuitesparseconfig=7.10.1=h4a8fc20_7100102
  - libtiff=4.7.0=hfce79cd_1
  - libumfpack=6.3.5=h7c2c975_7100102
  - libvorbis=1.3.7=h81086ad_2
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.5=hbbdcc80_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.7=h4a912ad_0
  - lz4-c=1.10.0=h286801f_1
  - metis=5.1.0=h15f6cfe_1007
  - mpfr=4.2.1=hb693164_3
  - ncurses=6.5=hee39554_0
  - nspr=4.38=heaf21c2_0
  - nss=3.118=h1c710a3_0
  - numpy=2.2.6=py310h4d83441_0
  - openexr=3.3.2=h04410fd_0
  - openjpeg=2.5.3=h889cd5d_1
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.0=h5503f6c_0
  - pcre2=10.46=h7125dd6_0
  - pillow=11.3.0=py310h5de80a5_3
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.4=hd74edd7_1002
  - python=3.10.15=hdce6c4c_2_cpython
  - python_abi=3.10=8_cp310
  - qt-main=5.15.15=hac936aa_5
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - suitesparse=7.10.1=h3071b36_7100102
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - vlfeat=0.9.21=hb547adb_1
  - wheel=0.45.1=py310hca03da5_0
  - xorg-libice=1.1.2=h5505292_0
  - xorg-libsm=1.2.6=h5505292_0
  - xorg-libx11=1.8.12=h6a5fb8c_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xorg-libxext=1.3.6=hd74edd7_0
  - xorg-libxfixes=6.0.2=hc919400_0
  - xorg-libxrender=0.9.12=h5505292_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - opencv-python==4.12.0.88
      - plyfile==1.1.3
      - scipy==1.15.3
      - tqdm==4.67.1
prefix: /Users/danaromero/miniconda3/envs/plycolmap
